/**
 * File header: Implements a worker-only Octopart adapter through the current Nexar GraphQL API.
 */

import { deriveAssetState, withCanonicalAssetTruth } from "@ee-library/shared/asset-state";
import { normalizeLifecycleStatus } from "@ee-library/shared/normalization";
import type { Asset, DatasheetRevision, InventoryStatus, LifecycleStatus, MetricUnit, PartMetric, SourceExtractionSignal } from "@ee-library/shared/types";
import type { NormalizedProviderPart, NormalizedSupplyOffering, NormalizedSupplyPriceBreak, ProviderAdapter, ProviderPartRequest, RawProviderPayload } from "../provider-adapters";
import { buildExactLookupCandidate } from "../provider-lookup-candidate";

/** OCTOPART_PROVIDER_ID is the canonical adapter id for Octopart data accessed through Nexar. */
const OCTOPART_PROVIDER_ID = "octopart";

/** DEFAULT_NEXAR_GRAPHQL_URL is the official Nexar GraphQL endpoint for supply queries. */
const DEFAULT_NEXAR_GRAPHQL_URL = "https://api.nexar.com/graphql";

/** DEFAULT_NEXAR_TOKEN_URL is the official Nexar identity endpoint for OAuth client credentials. */
const DEFAULT_NEXAR_TOKEN_URL = "https://identity.nexar.com/connect/token";

/** NEXAR_SUPPLY_SCOPE is the OAuth scope required for Octopart supply data. */
const NEXAR_SUPPLY_SCOPE = "supply.domain";

/** OCTOPART_SEARCH_URL is used only as a provenance fallback when a part URL is absent. */
const OCTOPART_SEARCH_URL = "https://octopart.com/search";

/** OCTOPART_SEARCH_LIMIT keeps exact MPN lookup bounded and deterministic. */
const OCTOPART_SEARCH_LIMIT = 5;

/** ACCESS_TOKEN_CACHE_SKEW_MS refreshes cached tokens before the provider rejects them. */
const ACCESS_TOKEN_CACHE_SKEW_MS = 60_000;

/** OCTOPART_PART_FIELDS is the shared GraphQL fragment used by exact-id and MPN queries. */
const OCTOPART_PART_FIELDS = `
fragment OctopartPartFields on SupPart {
  id
  mpn
  name
  shortDescription
  octopartUrl
  manufacturer {
    id
    name
    homepageUrl
  }
  category {
    id
    name
  }
  specs {
    attribute {
      id
      name
      shortname
    }
    displayValue
  }
  bestDatasheet {
    name
    url
  }
  sellers {
    company {
      id
      name
      homepageUrl
    }
    isAuthorized
    offers {
      sku
      inventoryLevel
      moq
      orderMultiple
      packaging
      factoryLeadDays
      onOrderQuantity
      clickUrl
      prices {
        quantity
        price
        currency
        convertedPrice
        convertedCurrency
      }
    }
  }
}
`;

/** OCTOPART_SEARCH_MPN_QUERY searches for exact MPN candidates with supplier offer context. */
const OCTOPART_SEARCH_MPN_QUERY = `
${OCTOPART_PART_FIELDS}
query OctopartSearchMpn($mpn: String!, $limit: Int!) {
  supSearchMpn(q: $mpn, limit: $limit, country: "US", currency: "USD") {
    hits
    results {
      description
      part {
        ...OctopartPartFields
      }
    }
  }
}
`;

/** CachedNexarToken keeps one short-lived access token between provider calls. */
interface CachedNexarToken {
  /** Bearer token returned by the Nexar identity service. */
  accessToken: string;
  /** Epoch milliseconds after which the token should not be reused. */
  expiresAtMs: number;
}

/** OctopartProviderConfig carries the runtime credentials and endpoints used by the adapter. */
interface OctopartProviderConfig {
  /** Optional already-generated access token for local tests or short-lived operator runs. */
  accessToken: string | null;
  /** OAuth client id generated by the Nexar portal. */
  clientId: string | null;
  /** OAuth client secret generated by the Nexar portal. */
  clientSecret: string | null;
  /** GraphQL endpoint override used by tests or private gateways. */
  graphqlUrl: string;
  /** OAuth token endpoint override used by tests or private gateways. */
  tokenUrl: string;
}

/** OctopartRawPayload preserves the selected Nexar result and the exact request context. */
interface OctopartRawPayload {
  /** Request shape that produced this raw payload. */
  request: {
    /** MPN used for an MPN-driven provider lookup. */
    mpn: string | null;
    /** Provider part id used for direct import, usually Nexar SupPart.id. */
    providerPartId: string | null;
    /** Optional manufacturer hint used only for exact disambiguation. */
    manufacturerName: string | null;
    /** Lookup mode used by the worker. */
    mode: "mpn" | "part_id";
  };
  /** Number of hits reported by supSearchMpn, or null for direct-id lookups. */
  hits: number | null;
  /** Result-level description when supSearchMpn provided one. */
  resultDescription: string | null;
  /** Selected Nexar/Octopart part payload. */
  part: OctopartPart;
}

/** OctopartSearchResult describes one result row from supSearchMpn. */
interface OctopartSearchResult {
  /** Result-level description text when present. */
  description?: string | null;
  /** Selected part payload. */
  part?: OctopartPart | null;
}

/** OctopartSearchResponseData describes the subset of GraphQL data read by the adapter. */
interface OctopartSearchResponseData {
  /** MPN search result set returned by Nexar. */
  supSearchMpn?: {
    /** Total hit count reported by Nexar. */
    hits?: number | null;
    /** Result rows returned for the query. */
    results?: OctopartSearchResult[] | null;
  } | null;
}

/** OctopartPartsResponseData describes the subset of direct-id GraphQL data read by the adapter. */
interface OctopartPartsResponseData {
  /** Direct SupPart rows returned by Nexar. */
  supParts?: OctopartPart[] | null;
}

/** OctopartPart is the permissive raw part shape returned by the GraphQL fragment. */
interface OctopartPart {
  /** Nexar SupPart id. */
  id?: string | null;
  /** Manufacturer part number. */
  mpn?: string | null;
  /** Provider display name when present. */
  name?: string | null;
  /** Provider short description when present. */
  shortDescription?: string | null;
  /** Octopart product page URL. */
  octopartUrl?: string | null;
  /** Manufacturer payload. */
  manufacturer?: OctopartManufacturer | null;
  /** Category payload. */
  category?: OctopartCategory | null;
  /** Technical specifications available under the account plan. */
  specs?: OctopartSpec[] | null;
  /** Best datasheet reference available under the account plan. */
  bestDatasheet?: OctopartDocument | null;
  /** Seller offer payloads available under the account plan. */
  sellers?: OctopartSeller[] | null;
}

/** OctopartManufacturer describes one raw manufacturer payload. */
interface OctopartManufacturer {
  /** Provider manufacturer id. */
  id?: string | null;
  /** Manufacturer display name. */
  name?: string | null;
  /** Manufacturer website when exposed. */
  homepageUrl?: string | null;
}

/** OctopartCategory describes one raw category payload. */
interface OctopartCategory {
  /** Provider category id. */
  id?: string | null;
  /** Category display name. */
  name?: string | null;
  /** Provider category path when exposed. */
  path?: unknown;
}

/** OctopartSpec describes one raw technical specification. */
interface OctopartSpec {
  /** Specification attribute metadata. */
  attribute?: {
    /** Provider attribute id. */
    id?: string | null;
    /** Attribute display name. */
    name?: string | null;
    /** Short machine-readable attribute name. */
    shortname?: string | null;
  } | null;
  /** Human-readable spec value from Nexar. */
  displayValue?: string | number | null;
}

/** OctopartDocument describes one raw document reference. */
interface OctopartDocument {
  /** Document display name when present. */
  name?: string | null;
  /** Document URL when present. */
  url?: string | null;
}

/** OctopartSeller describes one raw seller payload and its offer list. */
interface OctopartSeller {
  /** Seller company identity. */
  company?: {
    /** Provider company id. */
    id?: string | null;
    /** Seller display name. */
    name?: string | null;
    /** Seller website when exposed. */
    homepageUrl?: string | null;
  } | null;
  /** Whether Nexar marks the seller as manufacturer-authorized. */
  isAuthorized?: boolean | null;
  /** Offer rows exposed under this seller. */
  offers?: OctopartOffer[] | null;
}

/** OctopartOffer describes one raw distributor offer. */
interface OctopartOffer {
  /** Distributor SKU. */
  sku?: string | null;
  /** Inventory snapshot from Nexar. */
  inventoryLevel?: number | string | null;
  /** Minimum order quantity. */
  moq?: number | string | null;
  /** Order multiple. */
  orderMultiple?: number | string | null;
  /** Packaging label. */
  packaging?: string | null;
  /** Factory lead time in days. */
  factoryLeadDays?: number | string | null;
  /** On-order quantity when exposed. */
  onOrderQuantity?: number | string | null;
  /** Provider click-through URL retained only in raw payload. */
  clickUrl?: string | null;
  /** Price tiers exposed by the seller. */
  prices?: OctopartPrice[] | null;
}

/** OctopartPrice describes one raw price break row. */
interface OctopartPrice {
  /** Minimum quantity for the price tier. */
  quantity?: number | string | null;
  /** Unit price for the tier. */
  price?: number | string | null;
  /** Currency code for the tier. */
  currency?: string | null;
  /** Unit price converted to the requested GraphQL currency when exposed. */
  convertedPrice?: number | string | null;
  /** Currency code for convertedPrice when exposed. */
  convertedCurrency?: string | null;
}

/** SpecMetricCandidate carries one parsed provider spec before row ids are assigned. */
interface SpecMetricCandidate {
  /** Normalized metric key. */
  metricKey: string;
  /** Normalized metric unit. */
  unit: MetricUnit;
  /** Parsed single numeric metric value. */
  metricValue: number;
  /** Confidence score assigned to provider structured specs. */
  confidenceScore: number;
}

/** cachedNexarToken stores one token for the current process when client credentials are used. */
let cachedNexarToken: CachedNexarToken | null = null;

/** octopartProviderAdapter fetches and normalizes Octopart supply data through Nexar GraphQL. */
export const octopartProviderAdapter: ProviderAdapter = {
  async findExactPartCandidates(request) {
    if (!hasConfiguredOctopartCredentials()) {
      return [];
    }

    try {
      const rawPayload = await fetchOctopartRawPart({
        ...(request.manufacturerName ? { manufacturerName: request.manufacturerName } : {}),
        mpn: request.query
      });
      const normalizedPart = normalizeRawPart(rawPayload);

      return [buildExactLookupCandidate(normalizedPart, request.query)];
    } catch (error) {
      if (isOctopartNotFoundError(error) || isOctopartCredentialError(error)) {
        return [];
      }

      throw error;
    }
  },
  async fetchRawPart(request) {
    return fetchOctopartRawPart(request);
  },
  id: OCTOPART_PROVIDER_ID,
  async listAvailablePartRequests() {
    return [];
  },
  name: "Octopart via Nexar GraphQL",
  normalizeRawPart
};

/**
 * Clears the cached access token so focused tests can change credentials safely.
 */
export function resetOctopartProviderAuthCacheForTests(): void {
  cachedNexarToken = null;
}

/**
 * Fetches one raw Octopart/Nexar part by direct provider id or exact MPN.
 */
async function fetchOctopartRawPart(request: ProviderPartRequest): Promise<RawProviderPayload> {
  const providerPartId = normalizeOptionalText(request.providerPartId);
  const mpn = normalizeOptionalText(request.mpn);

  if (providerPartId) {
    try {
      return await fetchOctopartRawPartById(providerPartId, request);
    } catch (error) {
      if (!mpn || !isOctopartNotFoundError(error)) {
        throw error;
      }
    }
  }

  if (mpn) {
    return fetchOctopartRawPartByMpn(mpn, request);
  }

  throw new Error("Octopart/Nexar metadata record not found for unknown lookup");
}

/**
 * Fetches one raw part by Nexar SupPart id.
 */
async function fetchOctopartRawPartById(providerPartId: string, request: ProviderPartRequest): Promise<RawProviderPayload> {
  const data = await postNexarGraphql<OctopartPartsResponseData>(buildOctopartPartByIdQuery(providerPartId), {});
  const parts = Array.isArray(data.supParts) ? data.supParts : [];
  const part = parts.find((candidate) => normalizeOptionalText(candidate.id)?.toLowerCase() === providerPartId.toLowerCase()) ?? parts[0] ?? null;

  if (!part) {
    throw new Error(`Octopart/Nexar metadata record not found for ${providerPartId}`);
  }

  return buildRawPayload({
    hits: null,
    manufacturerName: request.manufacturerName ?? null,
    mode: "part_id",
    mpn: request.mpn ?? null,
    part,
    providerPartId,
    resultDescription: null
  });
}

/**
 * Fetches one raw part by exact MPN and optional manufacturer hint.
 */
async function fetchOctopartRawPartByMpn(mpn: string, request: ProviderPartRequest): Promise<RawProviderPayload> {
  const data = await postNexarGraphql<OctopartSearchResponseData>(OCTOPART_SEARCH_MPN_QUERY, {
    limit: OCTOPART_SEARCH_LIMIT,
    mpn
  });
  const resultSet = data.supSearchMpn;
  const results = Array.isArray(resultSet?.results) ? resultSet.results : [];
  const selectedResult = selectExactSearchResult(results, mpn, request.manufacturerName, request.providerPartId);

  if (!selectedResult?.part) {
    throw new Error(`Octopart/Nexar metadata record not found for ${mpn}`);
  }

  return buildRawPayload({
    hits: typeof resultSet?.hits === "number" ? resultSet.hits : null,
    manufacturerName: request.manufacturerName ?? null,
    mode: "mpn",
    mpn,
    part: selectedResult.part,
    providerPartId: request.providerPartId ?? null,
    resultDescription: selectedResult.description ?? null
  });
}

/**
 * Builds a direct-id query using a JSON-escaped literal so GraphQL ID/String schema variants both work.
 */
function buildOctopartPartByIdQuery(providerPartId: string): string {
  return `
${OCTOPART_PART_FIELDS}
query OctopartPartById {
  supParts(ids: ${JSON.stringify([providerPartId])}, currency: "USD") {
    ...OctopartPartFields
  }
}
`;
}

/**
 * Selects the exact MPN result, using manufacturer and provider-id hints only to disambiguate.
 */
function selectExactSearchResult(
  results: OctopartSearchResult[],
  mpn: string,
  manufacturerName: string | undefined,
  providerPartId: string | undefined
): OctopartSearchResult | null {
  const exactMpnResults = results.filter((result) => normalizeComparableText(result.part?.mpn) === normalizeComparableText(mpn));
  const exactProviderResult = normalizeOptionalText(providerPartId)
    ? exactMpnResults.find((result) => normalizeComparableText(result.part?.id) === normalizeComparableText(providerPartId))
    : undefined;

  if (exactProviderResult) {
    return exactProviderResult;
  }

  const exactManufacturerResult = normalizeOptionalText(manufacturerName)
    ? exactMpnResults.find((result) => normalizeComparableText(result.part?.manufacturer?.name).includes(normalizeComparableText(manufacturerName)))
    : undefined;

  return exactManufacturerResult ?? exactMpnResults[0] ?? null;
}

/**
 * Wraps a selected raw part in the provider-neutral raw payload envelope.
 */
function buildRawPayload({
  hits,
  manufacturerName,
  mode,
  mpn,
  part,
  providerPartId,
  resultDescription
}: {
  hits: number | null;
  manufacturerName: string | null;
  mode: "mpn" | "part_id";
  mpn: string | null;
  part: OctopartPart;
  providerPartId: string | null;
  resultDescription: string | null;
}): RawProviderPayload {
  return {
    fetchedAt: new Date().toISOString(),
    payload: {
      hits,
      part,
      request: {
        manufacturerName,
        mode,
        mpn,
        providerPartId
      },
      resultDescription
    } satisfies OctopartRawPayload,
    providerId: OCTOPART_PROVIDER_ID
  };
}

/**
 * Sends one authenticated GraphQL request to Nexar and returns its data object.
 */
async function postNexarGraphql<TData>(query: string, variables: Record<string, unknown>): Promise<TData> {
  const config = readOctopartProviderConfig();
  const accessToken = await readNexarAccessToken(config);
  const response = await fetch(config.graphqlUrl, {
    body: JSON.stringify({ query, variables }),
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    method: "POST"
  });

  if (!response.ok) {
    throw new Error(`Unable to fetch Octopart/Nexar GraphQL response (${response.status})`);
  }

  const envelope = await response.json() as Record<string, unknown>;
  const errors = readGraphqlErrors(envelope.errors);

  if (errors.length > 0) {
    throw new Error(`Octopart/Nexar GraphQL returned errors: ${errors.join("; ")}`);
  }

  if (!envelope.data || typeof envelope.data !== "object") {
    throw new Error("Octopart/Nexar GraphQL response did not include a data object");
  }

  return envelope.data as TData;
}

/**
 * Reads a usable Nexar bearer token from an explicit token or OAuth client credentials.
 */
async function readNexarAccessToken(config: OctopartProviderConfig): Promise<string> {
  if (config.accessToken) {
    return config.accessToken;
  }

  if (cachedNexarToken && cachedNexarToken.expiresAtMs > Date.now()) {
    return cachedNexarToken.accessToken;
  }

  if (!config.clientId || !config.clientSecret) {
    throw new Error("Octopart/Nexar credentials are not configured. Set NEXAR_ACCESS_TOKEN or NEXAR_CLIENT_ID and NEXAR_CLIENT_SECRET.");
  }

  const body = new URLSearchParams({
    client_id: config.clientId,
    client_secret: config.clientSecret,
    grant_type: "client_credentials",
    scope: NEXAR_SUPPLY_SCOPE
  });
  const response = await fetch(config.tokenUrl, {
    body,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    method: "POST"
  });

  if (!response.ok) {
    throw new Error(`Unable to fetch Octopart/Nexar access token (${response.status})`);
  }

  const payload = await response.json() as Record<string, unknown>;
  const accessToken = typeof payload.access_token === "string" && payload.access_token.trim().length > 0 ? payload.access_token.trim() : null;
  const expiresInSeconds = readPositiveNumber(payload.expires_in) ?? 24 * 60 * 60;

  if (!accessToken) {
    throw new Error("Octopart/Nexar access token response was missing access_token");
  }

  cachedNexarToken = {
    accessToken,
    expiresAtMs: Date.now() + Math.max(1, expiresInSeconds) * 1000 - ACCESS_TOKEN_CACHE_SKEW_MS
  };

  return accessToken;
}

/**
 * Reads provider config from environment variables without exposing secrets to callers.
 */
function readOctopartProviderConfig(): OctopartProviderConfig {
  return {
    accessToken: normalizeOptionalText(process.env.NEXAR_ACCESS_TOKEN),
    clientId: normalizeOptionalText(process.env.NEXAR_CLIENT_ID),
    clientSecret: normalizeOptionalText(process.env.NEXAR_CLIENT_SECRET),
    graphqlUrl: normalizeOptionalText(process.env.NEXAR_GRAPHQL_URL) ?? DEFAULT_NEXAR_GRAPHQL_URL,
    tokenUrl: normalizeOptionalText(process.env.NEXAR_TOKEN_URL) ?? DEFAULT_NEXAR_TOKEN_URL
  };
}

/**
 * Reports whether any credential path is configured so optional provider lookup can skip cleanly.
 */
function hasConfiguredOctopartCredentials(): boolean {
  const config = readOctopartProviderConfig();

  return Boolean(config.accessToken || (config.clientId && config.clientSecret));
}

/**
 * Returns concise GraphQL error messages without copying the full provider response.
 */
function readGraphqlErrors(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((entry) => entry && typeof entry === "object" && "message" in entry && typeof entry.message === "string" ? entry.message.trim() : "")
    .filter((message) => message.length > 0)
    .slice(0, 3);
}

/**
 * Normalizes one raw Octopart/Nexar payload into provider-neutral canonical records.
 */
function normalizeRawPart(rawPayload: RawProviderPayload): NormalizedProviderPart {
  const payload = readOctopartRawPayload(rawPayload);
  const part = payload.part;
  const mpn = readRequiredText(part.mpn, "part.mpn");
  const manufacturerName = readRequiredText(part.manufacturer?.name, "part.manufacturer.name");
  const providerPartKey = readProviderPartKey(part, manufacturerName, mpn);
  const providerPartSlug = slugify(providerPartKey);
  const identitySlug = `${slugify(manufacturerName)}-${slugify(mpn)}`;
  const partId = `part-octopart-${identitySlug}`;
  const manufacturerId = `mfr-octopart-${slugify(manufacturerName)}`;
  const packageName = readPackageName(part);
  const packageId = `pkg-octopart-${slugify(packageName)}`;
  const sourceRecordId = `source-octopart-${providerPartSlug}`;
  const datasheetAsset = buildDatasheetAsset(part, partId, providerPartSlug, sourceRecordId, rawPayload.fetchedAt);
  const datasheetRevisionId = `dsr-octopart-${providerPartSlug}`;
  const lastUpdatedAt = rawPayload.fetchedAt;

  return {
    accessoryRequirements: [],
    assets: datasheetAsset ? [datasheetAsset] : [],
    cableCompatibilities: [],
    companionRecommendations: [],
    connectorFamily: null,
    connectorFamilyConflicts: [],
    datasheetRevisions: [
      buildDatasheetRevision(part, partId, datasheetRevisionId, datasheetAsset?.id ?? null, sourceRecordId, lastUpdatedAt)
    ],
    extractionSignals: buildSourceExtractionSignals(part, partId, sourceRecordId, datasheetRevisionId, datasheetAsset?.id ?? null, providerPartSlug, lastUpdatedAt),
    generationWorkflows: [],
    manufacturer: {
      aliases: [],
      id: manufacturerId,
      name: manufacturerName,
      website: normalizeOptionalText(part.manufacturer?.homepageUrl)
    },
    mateRelations: [],
    metrics: buildMetrics(part, partId, datasheetRevisionId, sourceRecordId, providerPartSlug, lastUpdatedAt),
    package: {
      bodyHeightMm: null,
      bodyLengthMm: null,
      bodyWidthMm: null,
      id: packageId,
      packageName,
      pinCount: readPinCount(part, packageName),
      pitchMm: null
    },
    part: {
      category: readCategoryName(part),
      connectorFamilyId: null,
      description: buildDescription(part, payload.resultDescription, manufacturerName, mpn),
      id: partId,
      lastUpdatedAt,
      lifecycleStatus: readLifecycleStatus(part),
      manufacturerId,
      mpn,
      packageId,
      trustScore: 0.68
    },
    promotionAudits: [],
    reviewRecords: [],
    similarPartRelations: [],
    supplyOfferings: buildSupplyOfferings(part, partId, sourceRecordId, providerPartKey, providerPartSlug, rawPayload.fetchedAt),
    validationRecords: [],
    sourceRecord: {
      fetchedAt: rawPayload.fetchedAt,
      id: sourceRecordId,
      importErrorDetails: null,
      importStatus: "imported",
      lastUpdatedAt,
      normalizedAt: lastUpdatedAt,
      partId,
      providerId: OCTOPART_PROVIDER_ID,
      providerPartKey,
      rawPayload: rawPayload.payload,
      sourceLastImportedAt: lastUpdatedAt,
      sourceLastSeenAt: rawPayload.fetchedAt,
      sourceUrl: readSourceUrl(part, mpn)
    }
  };
}

/**
 * Reads and validates the raw payload envelope for this adapter.
 */
function readOctopartRawPayload(rawPayload: RawProviderPayload): OctopartRawPayload {
  if (rawPayload.providerId !== OCTOPART_PROVIDER_ID) {
    throw new Error(`Unexpected Octopart provider id: ${rawPayload.providerId}`);
  }

  const payload = rawPayload.payload as Partial<OctopartRawPayload> | null;

  if (!payload || typeof payload !== "object" || !payload.part || typeof payload.part !== "object") {
    throw new Error("Invalid Octopart/Nexar raw payload");
  }

  return payload as OctopartRawPayload;
}

/**
 * Builds a datasheet reference asset without implying the PDF is stored locally.
 */
function buildDatasheetAsset(part: OctopartPart, partId: string, providerPartSlug: string, sourceRecordId: string, lastUpdatedAt: string): Asset | null {
  const datasheetUrl = normalizeOptionalText(part.bestDatasheet?.url);

  if (!datasheetUrl) {
    return null;
  }

  const assetState = deriveAssetState({
    fileHash: null,
    sourceUrl: datasheetUrl,
    storageKey: null,
    validationStatus: "not_validated"
  });

  return withCanonicalAssetTruth({
    assetState,
    assetStatus: assetState,
    assetType: "datasheet",
    fileFormat: "pdf",
    fileHash: null,
    generationMethod: null,
    generationSourceAssetId: null,
    id: `asset-octopart-${providerPartSlug}-datasheet`,
    lastUpdatedAt,
    licenseMode: "metadata_only",
    partId,
    previewStatus: "not_available",
    providerId: OCTOPART_PROVIDER_ID,
    provenance: "trusted_external",
    sourceRecordId,
    sourceUrl: datasheetUrl,
    storageKey: null,
    validationStatus: "not_validated"
  });
}

/**
 * Builds a datasheet revision placeholder that keeps parsing confidence explicit.
 */
function buildDatasheetRevision(
  part: OctopartPart,
  partId: string,
  datasheetRevisionId: string,
  datasheetAssetId: string | null,
  sourceRecordId: string,
  lastUpdatedAt: string
): DatasheetRevision {
  return {
    fileAssetId: datasheetAssetId,
    id: datasheetRevisionId,
    lastUpdatedAt,
    pageCount: null,
    parseConfidence: 0,
    partId,
    pinTableStatus: "not_available",
    revisionDate: null,
    revisionLabel: part.bestDatasheet ? "Octopart datasheet reference" : "Octopart metadata reference",
    sourceRecordId
  };
}

/**
 * Builds source extraction signals from structured provider metadata without claiming reviewed CAD evidence.
 */
function buildSourceExtractionSignals(
  part: OctopartPart,
  partId: string,
  sourceRecordId: string,
  datasheetRevisionId: string,
  datasheetAssetId: string | null,
  providerPartSlug: string,
  lastUpdatedAt: string
): SourceExtractionSignal[] {
  const hasPackageSignal = readPackageName(part) !== "Unknown package" || readPinCount(part, "Unknown package") !== null;

  return [
    {
      assetId: datasheetAssetId,
      confidenceScore: hasPackageSignal ? 0.35 : 0,
      datasheetRevisionId,
      extractionSource: "provider_structured_metadata",
      extractionStatus: hasPackageSignal ? "needs_review" : "not_available",
      id: `sig-octopart-${providerPartSlug}-package`,
      lastUpdatedAt,
      notes: hasPackageSignal ? "Provider package or pin-count metadata was mapped; body and pitch dimensions were not extracted." : "No package/mechanical source signal was available in provider metadata.",
      partId,
      signalType: "package_mechanical_dimensions",
      sourceRecordId
    },
    {
      assetId: datasheetAssetId,
      confidenceScore: 0,
      datasheetRevisionId,
      extractionSource: "provider_structured_metadata",
      extractionStatus: "not_available",
      id: `sig-octopart-${providerPartSlug}-pin-table`,
      lastUpdatedAt,
      notes: "No reviewed pin table was extracted from the structured provider metadata.",
      partId,
      signalType: "pin_table",
      sourceRecordId
    },
    {
      assetId: null,
      confidenceScore: 0,
      datasheetRevisionId,
      extractionSource: "provider_structured_metadata",
      extractionStatus: "not_available",
      id: `sig-octopart-${providerPartSlug}-mechanical-drawing`,
      lastUpdatedAt,
      notes: "No mechanical drawing extraction signal was available in provider metadata.",
      partId,
      signalType: "mechanical_drawing",
      sourceRecordId
    }
  ];
}

/**
 * Builds normalized metric rows from structured specs that can be parsed conservatively.
 */
function buildMetrics(part: OctopartPart, partId: string, datasheetRevisionId: string, sourceRecordId: string, providerPartSlug: string, lastUpdatedAt: string): PartMetric[] {
  const specs = Array.isArray(part.specs) ? part.specs : [];
  const candidates = [
    readSpecMetric(specs, "resistance", ["resistance"], "ohm"),
    readSpecMetric(specs, "capacitance", ["capacitance"], "F"),
    readSpecMetric(specs, "inductance", ["inductance"], "H"),
    readSpecMetric(specs, "voltage_rating", ["voltage", "supply_voltage", "operating_voltage"], "V"),
    readSpecMetric(specs, "current_rating", ["current", "output_current"], "A"),
    readSpecMetric(specs, "frequency", ["frequency", "clock_frequency"], "Hz")
  ].filter((candidate): candidate is SpecMetricCandidate => candidate !== null);

  return candidates.map((candidate, index) => ({
    confidenceScore: candidate.confidenceScore,
    id: `metric-octopart-${providerPartSlug}-${candidate.metricKey}-${index + 1}`,
    lastUpdatedAt,
    maxValue: null,
    metricKey: candidate.metricKey,
    metricValue: candidate.metricValue,
    minValue: null,
    partId,
    sourceRecordId,
    sourceRevisionId: datasheetRevisionId,
    unit: candidate.unit
  }));
}

/**
 * Reads one metric candidate from the first matching provider spec.
 */
function readSpecMetric(specs: OctopartSpec[], metricKey: string, keyHints: string[], unit: MetricUnit): SpecMetricCandidate | null {
  const spec = findSpecByHints(specs, keyHints);
  const metricValue = parseEngineeringNumber(spec?.displayValue, unit);

  if (metricValue === null) {
    return null;
  }

  return {
    confidenceScore: 0.56,
    metricKey,
    metricValue,
    unit
  };
}

/**
 * Builds source-linked commercial snapshots from seller offers without treating them as live stock truth.
 */
function buildSupplyOfferings(
  part: OctopartPart,
  partId: string,
  sourceRecordId: string,
  providerPartKey: string,
  providerPartSlug: string,
  capturedAt: string
): NormalizedSupplyOffering[] {
  const sellers = Array.isArray(part.sellers) ? part.sellers : [];

  return sellers.flatMap((seller, sellerIndex) => {
    const sellerName = normalizeOptionalText(seller.company?.name) ?? `Octopart seller ${sellerIndex + 1}`;
    const offers = Array.isArray(seller.offers) ? seller.offers : [];

    return offers.flatMap((offer, offerIndex) =>
      buildSupplyOffering({
        capturedAt,
        offer,
        offerIndex,
        partId,
        providerPartKey,
        providerPartSlug,
        sellerIndex,
        sellerName,
        sourceRecordId
      })
    );
  });
}

/**
 * Builds one commercial snapshot row from a seller offer when any useful commercial signal exists.
 */
function buildSupplyOffering({
  capturedAt,
  offer,
  offerIndex,
  partId,
  providerPartKey,
  providerPartSlug,
  sellerIndex,
  sellerName,
  sourceRecordId
}: {
  capturedAt: string;
  offer: OctopartOffer;
  offerIndex: number;
  partId: string;
  providerPartKey: string;
  providerPartSlug: string;
  sellerIndex: number;
  sellerName: string;
  sourceRecordId: string;
}): NormalizedSupplyOffering[] {
  const sellerSlug = slugify(sellerName);
  const sku = normalizeOptionalText(offer.sku);
  const skuSlug = slugify(sku ?? `${offerIndex + 1}`);
  const offeringId = `supply-octopart-${providerPartSlug}-${sellerSlug}-${skuSlug}-${offerIndex + 1}`;
  const priceBreaks = buildPriceBreaks(offer.prices, offeringId, providerPartSlug, sellerSlug, skuSlug, capturedAt);
  const inventoryQuantity = readNullableInteger(offer.inventoryLevel);
  const onOrderQuantity = readNullableInteger(offer.onOrderQuantity);
  const leadTimeDays = readNullableInteger(offer.factoryLeadDays);
  const moq = readPositiveInteger(offer.moq) ?? readMoqFromPriceBreaks(priceBreaks);

  if (priceBreaks.length === 0 && inventoryQuantity === null && onOrderQuantity === null && leadTimeDays === null && moq === null) {
    return [];
  }

  return [
    {
      createdAt: capturedAt,
      currencyCode: priceBreaks[0]?.currencyCode ?? "USD",
      id: offeringId,
      inventoryQuantity,
      inventoryStatus: readInventoryStatus(inventoryQuantity, onOrderQuantity, leadTimeDays),
      lastSeenAt: capturedAt,
      leadTimeDays,
      moq,
      packaging: normalizeOptionalText(offer.packaging),
      partId,
      preferredRank: sellerIndex * 100 + offerIndex + 1,
      priceBreaks,
      providerId: OCTOPART_PROVIDER_ID,
      providerPartKey,
      providerSku: sku ? `${sellerName} SKU ${sku}` : sellerName,
      sourceRecordId,
      updatedAt: capturedAt
    }
  ];
}

/**
 * Builds normalized price tier rows from seller offer prices.
 */
function buildPriceBreaks(
  prices: OctopartPrice[] | null | undefined,
  offeringId: string,
  providerPartSlug: string,
  sellerSlug: string,
  skuSlug: string,
  capturedAt: string
): NormalizedSupplyPriceBreak[] {
  if (!Array.isArray(prices)) {
    return [];
  }

  return prices.flatMap((price, index) => {
    const minQuantity = readPositiveInteger(price.quantity);
    const unitPrice = readNonNegativeNumber(price.convertedPrice ?? price.price);
    const currencyCode = readCurrencyCode(price.convertedCurrency ?? price.currency);

    if (minQuantity === null || unitPrice === null) {
      return [];
    }

    return [
      {
        capturedAt,
        currencyCode,
        id: `price-octopart-${providerPartSlug}-${sellerSlug}-${skuSlug}-${currencyCode.toLowerCase()}-${minQuantity}-${index + 1}`,
        minQuantity,
        supplyOfferingId: offeringId,
        unitPrice
      }
    ];
  });
}

/**
 * Reads the lowest positive price tier quantity as the inferred MOQ.
 */
function readMoqFromPriceBreaks(priceBreaks: NormalizedSupplyPriceBreak[]): number | null {
  return priceBreaks.reduce<number | null>((lowest, priceBreak) => {
    if (lowest === null || priceBreak.minQuantity < lowest) {
      return priceBreak.minQuantity;
    }

    return lowest;
  }, null);
}

/**
 * Maps provider inventory fields to the snapshot status enum without making live-stock claims.
 */
function readInventoryStatus(inventoryQuantity: number | null, onOrderQuantity: number | null, leadTimeDays: number | null): InventoryStatus {
  if (inventoryQuantity !== null) {
    return inventoryQuantity > 0 ? "in_stock" : "out_of_stock";
  }

  if ((onOrderQuantity !== null && onOrderQuantity > 0) || leadTimeDays !== null) {
    return "backorder";
  }

  return "unknown";
}

/**
 * Reads a stable provider key, falling back to manufacturer and MPN only when the provider omits an id.
 */
function readProviderPartKey(part: OctopartPart, manufacturerName: string, mpn: string): string {
  return normalizeOptionalText(part.id) ?? `${manufacturerName}:${mpn}`;
}

/**
 * Reads the best known package label without inventing package certainty.
 */
function readPackageName(part: OctopartPart): string {
  const specs = Array.isArray(part.specs) ? part.specs : [];
  const packageSpec = findSpecByHints(specs, ["case_package", "package_case", "package"]);
  const value = normalizeOptionalText(packageSpec?.displayValue);

  return value ?? "Unknown package";
}

/**
 * Reads pin count from structured specs first, then from common package text suffixes.
 */
function readPinCount(part: OctopartPart, packageName: string): number | null {
  const specs = Array.isArray(part.specs) ? part.specs : [];
  const pinSpec = findSpecByHints(specs, ["pin_count", "number_of_pins", "pins"]);
  const parsedSpec = readPositiveInteger(pinSpec?.displayValue);

  if (parsedSpec !== null) {
    return parsedSpec;
  }

  const match = packageName.match(/(?:^|[-\s])(\d{1,3})(?:$|[^\d])/u);

  return match?.[1] ? Number(match[1]) : null;
}

/**
 * Reads category path text while keeping missing category evidence explicit.
 */
function readCategoryName(part: OctopartPart): string {
  const path = readCategoryPath(part.category?.path);
  const name = normalizeOptionalText(part.category?.name);

  return path ?? name ?? "Unknown";
}

/**
 * Reads a provider category path that may be an array of strings or objects.
 */
function readCategoryPath(value: unknown): string | null {
  if (typeof value === "string" && value.trim().length > 0) {
    return collapseWhitespace(value);
  }

  if (!Array.isArray(value)) {
    return null;
  }

  const segments = value.flatMap((segment) => {
    if (typeof segment === "string" && segment.trim().length > 0) {
      return [collapseWhitespace(segment)];
    }

    if (segment && typeof segment === "object" && "name" in segment && typeof segment.name === "string" && segment.name.trim().length > 0) {
      return [collapseWhitespace(segment.name)];
    }

    return [];
  });

  return segments.length > 0 ? segments.join(" / ") : null;
}

/**
 * Builds an engineer-readable description from provider text and identity context.
 */
function buildDescription(part: OctopartPart, resultDescription: string | null, manufacturerName: string, mpn: string): string {
  const description = normalizeOptionalText(part.shortDescription) ?? normalizeOptionalText(resultDescription) ?? normalizeOptionalText(part.name);

  return truncateDescription(description ?? `${manufacturerName} ${mpn}`);
}

/**
 * Reads lifecycle only from structured provider specs and otherwise returns unknown.
 */
function readLifecycleStatus(part: OctopartPart): LifecycleStatus {
  const specs = Array.isArray(part.specs) ? part.specs : [];
  const lifecycleSpec = findSpecByHints(specs, ["lifecycle_status", "part_lifecycle", "part_status", "status"]);

  return normalizeLifecycleStatus(normalizeOptionalText(lifecycleSpec?.displayValue));
}

/**
 * Reads the part source URL or builds a search URL fallback for provenance.
 */
function readSourceUrl(part: OctopartPart, mpn: string): string {
  const sourceUrl = normalizeOptionalText(part.octopartUrl);

  if (sourceUrl) {
    return sourceUrl;
  }

  const searchUrl = new URL(OCTOPART_SEARCH_URL);
  searchUrl.searchParams.set("q", mpn);

  return searchUrl.toString();
}

/**
 * Finds the first spec whose normalized name, short name, or id contains a hint.
 */
function findSpecByHints(specs: OctopartSpec[], hints: string[]): OctopartSpec | null {
  const normalizedHints = hints.map(normalizeComparableText);

  return specs.find((spec) => {
    const names = [
      normalizeOptionalText(spec.attribute?.shortname),
      normalizeOptionalText(spec.attribute?.name),
      normalizeOptionalText(spec.attribute?.id)
    ].flatMap((value) => value ? [normalizeComparableText(value)] : []);

    return names.some((name) => normalizedHints.some((hint) => name.includes(hint)));
  }) ?? null;
}

/**
 * Parses common electronics unit strings into normalized base units.
 */
function parseEngineeringNumber(value: unknown, unit: MetricUnit): number | null {
  const text = typeof value === "number" ? String(value) : typeof value === "string" ? value : "";
  const match = text.match(/([+-]?\d+(?:\.\d+)?)/u);

  if (!match?.[1]) {
    return null;
  }

  const parsed = Number(match[1]);

  if (!Number.isFinite(parsed)) {
    return null;
  }

  return parsed * readMetricMultiplier(text, unit);
}

/**
 * Reads unit prefixes from common provider display values.
 */
function readMetricMultiplier(text: string, unit: MetricUnit): number {
  const normalized = text.trim().toLowerCase();

  if (unit === "ohm") {
    if (/\b(mOhm|m ohm|milliohm|milli-ohm)\b/u.test(text)) return 0.001;
    if (/\b(kohm|k ohm|kiloohm)\b/u.test(normalized)) return 1_000;
    if (/\b(MOhm|M ohm)\b/u.test(text) || /\b(megohm|megaohm)\b/iu.test(text)) return 1_000_000;
  }

  if (unit === "F") {
    if (/\bpf\b/u.test(normalized)) return 1e-12;
    if (/\bnf\b/u.test(normalized)) return 1e-9;
    if (/\b(uf|microfarad)\b/u.test(normalized)) return 1e-6;
    if (/\b(mf|millifarad)\b/u.test(normalized)) return 1e-3;
  }

  if (unit === "H") {
    if (/\bnh\b/u.test(normalized)) return 1e-9;
    if (/\b(uh|microhenry)\b/u.test(normalized)) return 1e-6;
    if (/\b(mh|millihenry)\b/u.test(normalized)) return 1e-3;
  }

  if (unit === "V") {
    if (/\bmv\b/u.test(normalized)) return 1e-3;
    if (/\bkv\b/u.test(normalized)) return 1_000;
  }

  if (unit === "A") {
    if (/\bma\b/u.test(normalized)) return 1e-3;
    if (/\bua\b/u.test(normalized)) return 1e-6;
  }

  if (unit === "Hz") {
    if (/\bkhz\b/u.test(normalized)) return 1_000;
    if (/\bmhz\b/u.test(normalized)) return 1_000_000;
    if (/\bghz\b/u.test(normalized)) return 1_000_000_000;
  }

  return 1;
}

/**
 * Returns whether an error represents a normal no-match provider outcome.
 */
function isOctopartNotFoundError(error: unknown): boolean {
  return error instanceof Error && /Octopart\/Nexar metadata record not found/u.test(error.message);
}

/**
 * Returns whether an error means Octopart credentials are absent for optional lookup.
 */
function isOctopartCredentialError(error: unknown): boolean {
  return error instanceof Error && /Octopart\/Nexar credentials are not configured/u.test(error.message);
}

/**
 * Reads a required provider text value.
 */
function readRequiredText(value: unknown, fieldName: string): string {
  const normalized = normalizeOptionalText(value);

  if (!normalized) {
    throw new Error(`Invalid Octopart/Nexar field: ${fieldName}`);
  }

  return normalized;
}

/**
 * Reads optional provider text while trimming whitespace-only values to null.
 */
function normalizeOptionalText(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0 ? collapseWhitespace(value) : null;
}

/**
 * Reads a positive provider number from numeric or numeric-string values.
 */
function readPositiveNumber(value: unknown): number | null {
  const parsed = typeof value === "number" ? value : typeof value === "string" ? Number(value) : Number.NaN;

  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

/**
 * Reads a positive integer from provider numeric or numeric-string values.
 */
function readPositiveInteger(value: unknown): number | null {
  const parsed = readPositiveNumber(value);

  return parsed !== null && parsed >= 1 ? Math.trunc(parsed) : null;
}

/**
 * Reads a nullable integer from provider numeric or numeric-string values.
 */
function readNullableInteger(value: unknown): number | null {
  const parsed = typeof value === "number" ? value : typeof value === "string" ? Number(value) : Number.NaN;

  return Number.isFinite(parsed) && parsed >= 0 ? Math.trunc(parsed) : null;
}

/**
 * Reads a non-negative finite number from provider numeric or numeric-string values.
 */
function readNonNegativeNumber(value: unknown): number | null {
  const parsed = typeof value === "number" ? value : typeof value === "string" ? Number(value) : Number.NaN;

  return Number.isFinite(parsed) && parsed >= 0 ? parsed : null;
}

/**
 * Reads an ISO 4217 currency code and defaults to USD when the provider omits it.
 */
function readCurrencyCode(value: unknown): string {
  const candidate = typeof value === "string" ? value.trim().toUpperCase() : "USD";

  return /^[A-Z]{3}$/u.test(candidate) ? candidate : "USD";
}

/**
 * Collapses repeated provider whitespace into single spaces.
 */
function collapseWhitespace(value: string): string {
  return value.trim().replace(/\s+/gu, " ");
}

/**
 * Normalizes strings for exact-provider comparison only.
 */
function normalizeComparableText(value: unknown): string {
  return typeof value === "string" ? collapseWhitespace(value).toLowerCase() : "";
}

/** Maximum description length persisted to the parts table for keyword search. */
const MAX_NORMALIZED_DESCRIPTION_LENGTH = 200;

/**
 * Truncates long provider descriptions to the canonical parts table budget.
 */
function truncateDescription(value: string): string {
  if (value.length <= MAX_NORMALIZED_DESCRIPTION_LENGTH) {
    return value;
  }

  return value.slice(0, MAX_NORMALIZED_DESCRIPTION_LENGTH).trimEnd();
}

/**
 * Converts provider names and identifiers into deterministic lowercase id fragments.
 */
function slugify(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "") || "unknown";
}
